# Pythonイメージの取得
FROM python:3.8.6-slim-buster
# ワーキングディレクトリの指定
WORKDIR /usr/local/app
# モジュールを揃える
COPY requirements_worker.txt requirements.txt
COPY api/scraper_lib/requirements.txt requirements_lib.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r requirements_lib.txt
# 必要なファイルだけコピー
RUN mkdir api
COPY api/scraper_lib api/scraper_lib
COPY api/worker api/worker
COPY api/__init__.py api/__init__.py
# 起動環境設定
ENTRYPOINT ["rqworker"]
CMD [ "--url", "redis://gcir_redis" ]