version: '3.8'

services:
  db:
    container_name: gcir_mariadb
    hostname: mariadb
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ${VOLUME_DB_PATH}:/var/lib/mysql:delegated
    ports:
      - ${PORT_DB}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
  redis:
    container_name: gcir_redis
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - ${PORT_REDIS}:6379
  adminer:
    container_name: gcir_adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
    depends_on:
      - db
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile_amd64
    container_name: gcir_api
    volumes:
      - ${VOLUME_API_PATH}:/usr/local/app/static
    ports:
      - ${PORT_API}:5000
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile_worker
    container_name: gcir_worker
    volumes:
      - ${VOLUME_API_PATH}:/usr/local/app
    depends_on:
      - redis
