# ビルドできないのでモジュールはローカル側で揃えてアップロードしておく
# docker buildx build --t ghcr.io/gochiira/main-backend-depends:latest --platform linux/arm/v7 -t gochiira/main-backend-depends --file Dockerfile .
# Pythonイメージの取得
FROM python:3.8.6-slim-buster
# ワーキングディレクトリの指定
WORKDIR /usr/local/app
# モジュールを揃える
COPY requirements.txt requirements.txt
COPY blueprints/lib/requirements.txt requirements_lib.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r requirements_lib.txt
